name:                genetic-snakes
version:             0.1.0.0
github:              "wdhg/genetic-snakes"
license:             BSD3
author:              "wdhg"
maintainer:          "wdhgrant@gmail.com"
copyright:           "2020 wdhg"

# extra-source-files:
# - README.md
# - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/wdhg/genetic-snakes#readme>

dependencies:
- base >= 4.7 && < 5
- mtl >= 2.2 && < 3
- MonadRandom >= 0.5 && < 0.6
- hspec >= 2.7 && < 2.8

library:
  source-dirs: src

executables:
  genetic-snakes-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - genetic-snakes

tests:
  genetic-snakes-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - genetic-snakes
